spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wxbot?serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8080
robot:
  groupid: 48408656825@chatroom #测试群
  groupidA: 43209303317@chatroom #闲聊群
  groupidB: 49083670583@chatroom #派单群