spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wxbot?serverTimezone=UTC
    username: wxbot
    password: mEPxKmNJGNEWxezn

server:
  port: 18080
robot:
  remindWeChat: 25984982360415668@openim #派单无人接单@微信  米粒 25984982360415668@openim
  groupidTest: 48408656825@chatroom #测试群
  groupidA: 43209303317@chatroom #闲聊群
  groupidB: 49083670583@chatroom #派单群
  dispatchGroup: 43113905663@chatroom,47595562713@chatroom,43934705390@chatroom #派单群  金牌、正式、实习