spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wxbot?serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 1397
robot:
  remindWeChat: 25984983585997042@openim #派单无人接单@微信 小高
  groupidB: 49083670583@chatroom #派单群
  dispatchGroup: 48383963444@chatroom
  #指定群  测试